version: 2

jobs:
  build_and_test:
    docker:
      - image: robotlocomotion/circleci:xenial

    working_directory: ~/underactuated

    steps:
      - checkout

      - run:
          name: setup
          command: ./scripts/continuous_integration/circle_ci/setup

      - run: echo 'export PYTHONPATH=/opt/drake/lib/python2.7/site-packages:${PYTHONPATH}' >> $BASH_ENV

      - run:
          name: build and test
          command: ./scripts/continuous_integration/circle_ci/build_test

workflows:
  version: 2
  pr-workflow:
    jobs:
       - build_and_test
  nightly-workflow:
    triggers:
      - schedule:
          cron: "0 4 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build_and_test
